services:
  - type: web
    name: manufaturing-backend
    runtime: node
    repo: https://github.com/adolfodev10/manufaturing-backend
    branch: main
    buildCommand: npm ci && npx prisma migrate deploy && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CROSS_ORIGIN
        value: https://eko-manufaturing.vercel.app
