import { FastifyInstance } from "fastify";
import { AuthRoutes } from "./Auth";
import { BackupRoutes } from "./Backup";
import { CaixaRoutes } from "./Caixa";
import { CategoriasRoutes } from "./Categorias";
import { ClientRoutes } from "./Client";
import { ConfiguracoesRoutes } from "./Configuracoes";
import { DividasRoutes } from "./Dividas";
import { FaturasRoutes } from "./Faturas";
import { FormulasRoutes } from "./Formulas";
import { FornecedoresRoutes } from "./Fornecedores";
import { InventarioRoutes } from "./Inventario";
import { LogsRoutes } from "./Logs";
import { MateriasPrimasRoutes } from "./MateriasPrimas";
import { NotificationRoutes } from "./Notification";
import { PermissoesRoutes } from "./Permissoes";
import { PerfilRoutes } from "./Perfil";
import { ProducaoRoutes } from "./Producao";
import { ProductRoutes } from "./Product";
import { StockRoutes } from "./Stock";
import { SmsRoutes } from "./sms.routes";
import { UserRoutes } from "./User";
import { VendaRoutes } from "./Venda";

export async function Routes(app: FastifyInstance) { 
    app.register(AuthRoutes);
    app.register(BackupRoutes);
    app.register(CaixaRoutes);
    app.register(CategoriasRoutes);
    app.register(ClientRoutes);
    app.register(ConfiguracoesRoutes);
    app.register(DividasRoutes);
    app.register(FaturasRoutes);
    app.register(FormulasRoutes);
    app.register(FornecedoresRoutes);
    app.register(InventarioRoutes);
    app.register(LogsRoutes);
    app.register(MateriasPrimasRoutes);
    app.register(NotificationRoutes);
    app.register(PermissoesRoutes);
    app.register(PerfilRoutes);
    app.register(ProducaoRoutes);
    app.register(ProductRoutes);
    app.register(StockRoutes);
    app.register(SmsRoutes);
    app.register(UserRoutes);
    app.register(VendaRoutes);
}
